import { useEffect, useState } from 'react'
import { useAuth } from '../context/AuthContext'
import { supabase, type Content, type ContentType } from '../lib/supabase'
import { Layout } from '../components/Layout'
import { ContentTypeBadge, AITag } from '../components/Badges'
import { EmptyState, Modal, Spinner } from '../components/ui'
import { format } from 'date-fns'
import { Upload, FileText, Inbox, Bot, CircleCheck as CheckCircle2, Drama as Instagram, TriangleAlert as AlertTriangle } from 'lucide-react'

export default function Dashboard() {
  const { profile } = useAuth()
  const [items, setItems] = useState<Content[]>([])
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState<Content | null>(null)
  const [uploadOpen, setUploadOpen] = useState(false)
  const [filter, setFilter] = useState<'all' | 'ai' | 'mine'>('all')

  useEffect(() => {
    if (!profile) return
    const load = async () => {
      const { data } = await supabase
        .from('content')
        .select('*')
        .eq('user_id', profile.id)
        .order('created_at', { ascending: false })
      if (data) setItems(data as Content[])
      setLoading(false)
    }
    load()
  }, [profile])

  const filtered = items.filter((item) => {
    if (filter === 'ai') return item.ai_generated
    if (filter === 'mine') return !item.ai_generated
    return true
  })

  const aiCount = items.filter((i) => i.ai_generated).length

  return (
    <Layout>
      <div className="mb-8 flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="font-display text-3xl font-extrabold tracking-tight text-white">
            Your <span className="text-gold glow-text">Content</span>
          </h1>
          <p className="mt-1 text-sm text-slate-400">
            Everything you've uploaded — GDs, videos, and posts. AI-generated content appears here automatically.
          </p>
        </div>
        <button onClick={() => setUploadOpen(true)} className="btn-gold">
          <Upload size={18} /> Upload Content
        </button>
      </div>

      {/* AI Generated Banner */}
      {aiCount > 0 && (
        <div className="mb-6 flex items-center gap-3 rounded-lg border border-gold/20 bg-gold/[0.06] p-4 animate-fade-in">
          <div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-gold/10">
            <Bot size={20} className="text-gold" />
          </div>
          <div className="min-w-0 flex-1">
            <p className="text-sm font-semibold text-gold">AI Auto-Generated Content Available</p>
            <p className="text-xs text-slate-400">
              {aiCount} item{aiCount > 1 ? 's' : ''} generated by AI. Successfully generated — please contact respective member to upload to Instagram.
            </p>
          </div>
        </div>
      )}

      {/* Filter tabs */}
      <div className="mb-6 inline-flex rounded-lg border border-white/10 bg-white/[0.02] p-1">
        {(['all', 'ai', 'mine'] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`rounded-md px-4 py-1.5 text-sm font-semibold transition ${
              filter === f ? 'bg-gold/15 text-gold' : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            {f === 'all' ? 'All' : f === 'ai' ? 'AI-Generated' : 'My Uploads'}
          </button>
        ))}
      </div>

      {loading ? (
        <div className="grid place-items-center py-24"><Spinner size={32} /></div>
      ) : filtered.length === 0 ? (
        <EmptyState
          icon={<Inbox size={40} />}
          title="No content yet"
          subtitle="Upload your first GD, video, or post to see it here. AI-generated content will also appear here automatically."
          action={<button onClick={() => setUploadOpen(true)} className="btn-gold"><Upload size={18} /> Upload Content</button>}
        />
      ) : (
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
          {filtered.map((item) => (
            <button
              key={item.id}
              onClick={() => setSelected(item)}
              className="card card-hover p-5 text-left animate-fade-in"
            >
              <div className="mb-3 flex items-center justify-between">
                <ContentTypeBadge type={item.type} />
                {item.ai_generated && <AITag />}
              </div>
              <h3 className="line-clamp-2 font-display text-base font-bold text-slate-100">{item.topic}</h3>
              {item.ai_generated && (
                <div className="mt-3 flex items-center gap-2 rounded-md border border-gold/20 bg-gold/[0.06] px-3 py-2">
                  <CheckCircle2 size={13} className="shrink-0 text-gold" />
                  <p className="text-[11px] font-medium text-gold">
                    Successfully generated — contact respective member to upload to Instagram
                  </p>
                </div>
              )}
              <p className="mt-3 text-xs text-slate-500">
                {item.ai_generated ? 'AI Generated ' : 'Uploaded '}
                {format(new Date(item.created_at), 'd MMM yyyy')}
              </p>
            </button>
          ))}
        </div>
      )}

      <Modal open={!!selected} onClose={() => setSelected(null)} title="Content Detail" maxWidth="max-w-2xl">
        {selected && <ContentDetail item={selected} />}
      </Modal>

      <Modal open={uploadOpen} onClose={() => setUploadOpen(false)} title="Upload Content" maxWidth="max-w-xl">
        <UploadForm onDone={() => { setUploadOpen(false); window.location.reload() }} />
      </Modal>
    </Layout>
  )
}

function ContentDetail({ item }: { item: Content }) {
  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center gap-2">
        <ContentTypeBadge type={item.type} />
        {item.ai_generated && <AITag />}
      </div>
      <h3 className="font-display text-xl font-bold text-white">{item.topic}</h3>
      <p className="text-sm text-slate-400">
        {item.ai_generated ? 'AI Generated ' : 'Uploaded '}
        {format(new Date(item.created_at), 'd MMM yyyy, HH:mm')}
      </p>

      {item.ai_generated && (
        <div className="flex items-start gap-3 rounded-lg border border-gold/20 bg-gold/[0.06] p-4">
          <CheckCircle2 size={18} className="mt-0.5 shrink-0 text-gold" />
          <div>
            <p className="text-sm font-semibold text-gold">Successfully Generated</p>
            <p className="mt-1 text-xs text-slate-400">
              This content was auto-generated by AI. Please contact the respective member to upload it to Instagram.
            </p>
            <a
              href="https://www.instagram.com/"
              target="_blank"
              rel="noreferrer"
              className="mt-2 inline-flex items-center gap-1.5 text-xs font-medium text-gold hover:text-gold-soft"
            >
              <Instagram size={13} /> Open Instagram
            </a>
          </div>
        </div>
      )}

      {item.description && (
        <div className="rounded-lg border border-white/[0.06] bg-white/[0.02] p-4">
          <p className="whitespace-pre-wrap text-sm leading-relaxed text-slate-300">{item.description}</p>
        </div>
      )}
      {item.file_url && item.type === 'video' && (
        <div className="overflow-hidden rounded-lg border border-white/10">
          <video src={item.file_url} controls className="w-full" />
        </div>
      )}
      {item.file_url && item.type !== 'video' && (
        <a href={item.file_url} target="_blank" rel="noreferrer" className="btn-ghost w-full">
          <FileText size={16} /> View attached file
        </a>
      )}
      {!item.file_url && !item.description && (
        <p className="text-sm text-slate-500">No additional media attached.</p>
      )}
    </div>
  )
}

function UploadForm({ onDone }: { onDone: () => void }) {
  const { profile } = useAuth()
  const [type, setType] = useState<ContentType>('gd')
  const [topic, setTopic] = useState('')
  const [description, setDescription] = useState('')
  const [file, setFile] = useState<File | null>(null)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!profile) return
    if (!topic.trim()) { setError('Topic is required.'); return }
    setSaving(true)
    setError(null)
    let fileUrl: string | null = null
    if (file) {
      const ext = file.name.split('.').pop()
      const path = `content/${profile.id}/${Date.now()}.${ext}`
      const { error: upErr } = await supabase.storage.from('content').upload(path, file)
      if (upErr) { setError(upErr.message); setSaving(false); return }
      const { data: pub } = supabase.storage.from('content').getPublicUrl(path)
      fileUrl = pub.publicUrl
    }
    const { error: insErr } = await supabase.from('content').insert({
      user_id: profile.id,
      type,
      topic: topic.trim(),
      description: description.trim() || null,
      file_url: fileUrl,
      ai_generated: false,
    })
    if (insErr) { setError(insErr.message); setSaving(false); return }
    onDone()
  }

  return (
    <form onSubmit={submit} className="space-y-5">
      <div>
        <label className="label">Content Type</label>
        <div className="grid grid-cols-3 gap-2">
          {(['gd', 'video', 'post'] as ContentType[]).map((t) => (
            <button
              key={t}
              type="button"
              onClick={() => setType(t)}
              className={`rounded-md border px-3 py-2.5 text-sm font-semibold uppercase transition ${
                type === t ? 'border-gold/50 bg-gold/10 text-gold' : 'border-white/10 bg-white/[0.02] text-slate-400 hover:border-white/20'
              }`}
            >
              {t}
            </button>
          ))}
        </div>
      </div>
      <div>
        <label className="label">Topic</label>
        <input className="input" value={topic} onChange={(e) => setTopic(e.target.value)} placeholder="e.g. Leadership in Tech" />
      </div>
      <div>
        <label className="label">Description (optional)</label>
        <textarea className="input min-h-[100px] resize-y" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Notes or script…" />
      </div>
      <div>
        <label className="label">Attach file (optional)</label>
        <label className="flex cursor-pointer items-center justify-center gap-2 rounded-md border border-dashed border-white/15 bg-white/[0.02] px-4 py-6 text-sm text-slate-400 transition hover:border-gold/30 hover:text-slate-300">
          {file ? <span className="text-slate-200">{file.name}</span> : <><Upload size={16} /> Choose a file</>}
          <input type="file" className="hidden" onChange={(e) => e.target.files?.[0] && setFile(e.target.files[0])} />
        </label>
      </div>
      {error && <p className="rounded-md border border-crimson/30 bg-crimson/10 px-4 py-2.5 text-sm text-crimson">{error}</p>}
      <button type="submit" disabled={saving} className="btn-gold w-full py-3">
        {saving ? <Spinner size={18} /> : <Upload size={18} />} {saving ? 'Uploading…' : 'Upload'}
      </button>
    </form>
  )
}
